### ISSUE TITLE
Not opening .IMG files

### ISSUE THREAD

**Issue by JDat** [Bs0Dd/GRiDISKCOM#2]
Small bug with case sensitivity when opening disk images. No problems when there is .img files, but won't show .IMG files. Should be easy fix in GUI.

**Comment by JDat** [comment]
I am using Lubuntu 18.04
Probably problem is on gtk side.

**Comment by Bs0Dd** [comment]
Yes, the problem seems to be in the GTK dialog, which file mask is case sensitive (unlike Qt and Windows dialogs). I don't know how to fix this while still working adequately with Qt and Windows windows. However, in the new version, I added the "All files (*)" item, so that the desired image can, if necessary, be selected through it. Or use drag-and-drop. There's a self-contained, case-insensitive file extension check.

**Comment by JDat** [comment]
"All files (*)" fix looks good for me.
